version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/backend

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ubuntu

  Install:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start-application.sh
      timeout: 300
      runas: ubuntu
